### ISSUE TITLE
Standard for Dragonfly  module 

### ISSUE THREAD

**Issue by ghost** [dragonfly-tech/dragonfly#314]
### Introduction

Reusing someone else's code is good programming practice.

It will be great if the Dragonfly developers, who do not want to add their changes to the Dragonfly code (for various reasons), will create their add-ons according to some standard. For example using the "plugin" package.

### My suggestion

When I want to write a separate module for Dragonfly, I make a separate package with init functions. Then, in main.go, I import the modules I need using the "stub"

What's you mind about it? Wait for comments

**Comment by arfush** [comment]
> Please be more in depth, whats a "stub" in this context?

For example:
```golang
import _ "github.com/user/df-module"
```


> Is there a need of a standard? every module is going to need different things, just read the doc to find what's the setup functions and what it takes

I think that the standard will make it possible to make a single system of initialization of modules, which will make it easier for developers to understand the code. For some things, I think you can make special "interfaces". For example: MultiHandler.

> I fail to see the benefits of having a standard, reading docs is not that hard

It will become even easier :)

> Are you aware about that events handler are singular? even if i can have a standardized setup functions, you still need to be responsible of recieving and forwarding events to the module...

This is indeed a problem for the standard. Maybe you should change the handler? In future versions

**Comment by arfush** [comment]
> I don't really understand what this issue is for exactly

Please read my answer above :)

**Comment by Sandertv** [comment]
While fundamentally, I agree with `Reusing someone else's code is good programming practice.`. I don't feel like a standard like this necessarily achieves that. Currently, people can simply expose their own handlers and libraries so that other people can use them in whichever way they want. 

Say, for example, you have your own `player.Handler` that does something when the player moves: For example, it stops movement under a certain circumstance. The `player.Handler` of the library you import might have a handler for movement too, which you would only want to call if you don't already stop movement at a given moment. This kind of behaviour requires control, and you can't obtain that kind of control with an automatic system like you described.

I think the fundamental thing with Dragonfly is to understand that it is primarily aimed at developers looking to write a full server. Re-using code is good, but a system that (at least to an extent) functions similarly to plugins is just not necessarily something we're after because it limits control over the behaviour of libraries.

**Comment by Lucaskyy** [comment]
Reading your suggestions, this kind of feels like mixins. Is that what you mean?
